# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelRunStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('duration', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.UUIDField(verbose_name='The id from contentcuration.models.Channel')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('version', models.IntegerField(default=0)),
                ('source_domain', models.CharField(blank=True, max_length=300, null=True)),
                ('source_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user_registered_by', models.EmailField(blank=True, max_length=200, null=True)),
                ('user_token', models.CharField(blank=True, max_length=200, null=True)),
                ('content_server', models.URLField(default='https://develop.contentworkshop.learningequality.org', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ContentChannelRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chef_name', models.CharField(max_length=200)),
                ('ricecooker_version', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.ContentChannel')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.FloatField()),
                ('message', models.TextField()),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.ContentChannelRun')),
            ],
        ),
        migrations.AddField(
            model_name='channelrunstage',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.ContentChannelRun'),
        ),
    ]
